#!/usr/bin/env python

import time
import praw
import sys
import MySQLdb
import logging

done = False
username = ' '
password = ' '
dbUsername = ' '
dbPassword = ' '
db = None

class ApplicationItem:
	def __init__(self, index, author, text):
		self.index = index
		self.author = author
		self.text = text

def main():
	global username
	global password
	global dbUsername
	global dbPassword
	logging.basicConfig(filename='/var/log/spinalbot.log', level=logging.INFO, format='%(asctime)s %(message)s')
	if len(sys.argv) < 5:
		logging.error('Invalid arguments. Must provide reddit user, reddit pass, sql user, sql pass')#print 'Error: you must provide reddit username and password, as well as sql username and password!'
		sys.exit()

	logging.info('Spinalbot daemon launched.')	
	username = sys.argv[1]
	password = sys.argv[2]
	dbUsername = sys.argv[3]
	dbPassword = sys.argv[4]
	
	open_database()
	listener_thread()

def open_database():
	global db
	db = MySQLdb.connect('localhost', dbUsername, dbPassword, 'Spinalcraft')
	logging.info('Database connection established.')
	cursor = db.cursor()
	query = """CREATE TABLE IF NOT EXISTS Applications (
						id INT PRIMARY KEY AUTO_INCREMENT,
						author VARCHAR(32),
						text VARCHAR(3000),
						unread TINYINT,
						discarded TINYINT)"""
	try:
		cursor.execute(query)
		db.commit()
	except MySQLdb.Error, e:
		db.rollback()
		logging.info("MySQL Error [%d]: %s" % (e.args[0], e.args[1])) 

def insert_application(author, text):
	cursor = db.cursor()
	query = """INSERT INTO Applications (author, text, unread, discarded) 
							VALUES (%s, %s, 1, 0)"""
	params = author, text
	try:
		cursor.execute(query, params)
		db.commit()
		logging.info("Inserted application into database.")
	except MySQLdb.Error, e:
		db.rollback()
		logging.info("MySQL Error [%d]: %s" % (e.args[0], e.args[1])) 

def notify(name):
	r = get_session(username, password)
	try:
		r.send_message(name, 'Welcome!', 'Welcome to Spinalcraft! I just added you, [have fun!](/r/spinalcraft)')
	except praw.errors.InvalidUser:
		logging.error("Notify error: reddit user %s does not exist!" % (name))

def get_session(user, pwd):
	r = praw.Reddit('a')
	r.login(username = user, password = pwd)
	return r

def listener_thread():
	r = get_session(username, password)

	while True:
		unread = r.get_unread()	
		try:
			for message in unread:
				logging.info("%s received reddit message from %s" % (username, message.author.name))
				r.send_message('DoctorSauce', 'Application from ' + message.author.name, message.body)
				logging.info("Forwarded to DoctorSauce.")
				message.mark_as_read()
				insert_application(message.author.name, message.body)
				if isinstance(message, praw.objects.Moderatable):
					r.send_message(message.author.name, 'Thanks for applying to Spinalcraft!', 
						'Your app has been filed and is waiting to be processed. This can take anywhere from several minutes to a few hours. It really just depends on whether Parker is on top of things right now :)')			
					message.remove()
		except HttpError:
			logging.warning("HTTP Error caught. Ignoring...")
		time.sleep(3)

if __name__ == '__main__':
	main()
